export const DOM = {
  canvas: document.querySelector("#scene"),
  layout: document.querySelector("#layout"),
  content: document.querySelector("#content"),
  title: document.querySelector("#title"),
  subtitle: document.querySelector("#subtitle"),
  description: document.querySelector("#description"),
  descriptionToggle: document.querySelector("#descriptionToggle"),
  nextButton: document.querySelector("#nextButton"),
  buttonText: document.querySelector("#buttonText"),
  counter: document.querySelector("#counter"),
  progressFill: document.querySelector("#progressFill"),
  state: document.querySelector("#state"),
  error: document.querySelector("#errorMessage"),
  rail: document.querySelector("#rail"),
  railDots: document.querySelectorAll(".rail-dot"),
  gate: document.querySelector("#gate"),
  gateYes: document.querySelector("#gateYes"),
  gateNo: document.querySelector("#gateNo"),
  gateContinue: document.querySelector("#gateContinue"),
  gatePanelQuestion: document.querySelector("#gatePanelQuestion"),
  gatePanelMessage: document.querySelector("#gatePanelMessage"),
  gateHint: document.querySelector("#gateHint")
};
